services:
  frontend:
    image: typescript-sveltekit:latest
    container_name: web_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - KOTLIN_SPRING_URL=http://backend:8080/api
  backend:
    image: kotlin-spring:latest
    container_name: web_backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - DB_URL=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DEEPSEEK_API_KEY=
      - DEEPSEEK_BASE_URL=https://api.deepseek.com/chat/completions
      - MISTRAL_API_KEY=
      - MISTRAL_BASE_URL=https://api.mistral.ai/v1/chat/completions
      - SENTENCE_TRANSFORMER_URL=http://microservice:8000/api/similarity

  microservice:
    image: python-fastapi:latest
    container_name: web_microservice
    ports:
      - "8000:8000"
    networks:
      - app-network

  nginx:
    image: web-nginx:latest
    container_name: web_ngnix
    ports:
      - "80:80"
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge