services:
  frontend:
    image: typescript-sveltekit:latest
    container_name: web_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - KOTLIN_SPRING_URL=
  backend:
    image: kotlin-spring:latest
    container_name: web_backend
    ports:
      - "8080:8080"
    networks:
      - app-network
    environment:
      - DB_URL=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DEEPSEEK_API_KEY=
      - DEEPSEEK_BASE_URL=
      - MISTRAL_API_KEY=
      - MISTRAL_BASE_URL=
      - SENTENCE_TRANSFORMER_URL=


  nginx:
    image: web-nginx:latest
    container_name: web_ngnix
    ports:
      - "80:80"
    networks:
      - app-network
    
  fastapi:
    image: python-fastapi:latest
    container_name: web_fastapi
    ports:
      - "8000:8000"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge